### ISSUE TITLE
Not work with manjaro-pipewire on Huawei Matebook 16s

### ISSUE THREAD

**Issue by canack** [Smoren/huawei-ubuntu-sound-fix#16]
I use fresh Manjaro, by default uses pipewire.
But this fix doesn't work. Do you have any tricks to make it work?

**Comment by dexxhawk** [comment]
The same problem.  It helps with jack headphones, they work fine, but speakers still won't work

**Comment by canack** [comment]
Hi @dexxhawk 
Can you run uninstall.sh and can you install `easyeffects`  on your system?
`sudo pacman -S easyeffects`
Then, can you open the easyeffects and try to run any music on your browser?

I can get the sound from speaker. May you need to go system settings > sound to switch easyeffects to it work.

**Comment by dexxhawk** [comment]
@canack, Thanks for advice but it didn't help. Luckily, I installed the new version that came out 3 days ago and now it works. @Smoren, Thanks! 
So strange situation because I read that in kernel 6.8 there will be added a support for Huawei sound cards but now I'm running 6.8 and the problem hasn't gone

**Comment by canack** [comment]
@dexxhawk wow, I'll try. Thank you for advice. 🙏

**Comment by canack** [comment]
@dexxhawk Thank you for updated me! It works 🚀 

Also thanks, @Smoren 🥇
